#pragma once

#include "particle/effects/acceleration.h"
#include "particle/effects/converge.h"
#include "particle/effects/jitter.h"
#include "particle/effects/limitPlane.h"
#include "particle/effects/radiusConverge.h"
#include "particle/effects/turn.h"
#include "particle/transitions/alpha.h"
#include "particle/transitions/color.h"
#include "particle/transitions/scale.h"
#include "particle/transitions/texture.h"
#include "particle/manager.h"
#include "particle/particle.h"
#include "particle/spawnInfo.h"
#include "particle/system.h"
#include "particle/texture.h"
#include "particle/transition.h"