#pragma once

enum IMouseButtons
{
    MOUSE_BT_LEFT,
    MOUSE_BT_RIGHT,
    MOUSE_BT_MIDDLE,
    MOUSE_BT_X_POS,
    MOUSE_BT_Y_POS,
    MOUSE_BT_X_MOVE,
    MOUSE_BT_Y_MOVE,
    MOUSE_BT_X_MOVE_L,
    MOUSE_BT_Y_MOVE_L,
    MOUSE_BT_X_MOVE_R,
    MOUSE_BT_Y_MOVE_R,
    MOUSE_BT_X_MOVE_M,
    MOUSE_BT_Y_MOVE_M,
    MOUSE_BT_SCROLL_X_POS,
    MOUSE_BT_SCROLL_Y_POS,
    MOUSE_BT_SCROLL_X_MOVE,
    MOUSE_BT_SCROLL_Y_MOVE,

    MOUSE_BT_COUNT
};

enum IMenuButtons
{
    MENU_BT_UP,
    MENU_BT_DOWN,
    MENU_BT_LEFT,
    MENU_BT_RIGHT,
    MENU_BT_SELECT,
    MENU_BT_BACK,

    MENU_BT_COUNT
};

enum IFreeCamButtons
{
    FREECAM_BT_FORWARD,
    FREECAM_BT_BACKWARD,
    FREECAM_BT_FORWARD_BACKWARD_AN,
    FREECAM_BT_LEFT,
    FREECAM_BT_RIGHT,
    FREECAM_BT_LEFT_RIGHT_AN,
    FREECAM_BT_UP,
    FREECAM_BT_DOWN,
    FREECAM_BT_UP_DOWN_AN,
    FREECAM_BT_ROT_X_AN,
    FREECAM_BT_ROT_Y_AN,

    FREECAM_BT_COUNT
};

enum ICameraButtons
{
    CAMERA_BT_ORBIT_UPWARDS,
    CAMERA_BT_ORBIT_DOWNWARDS,
    CAMERA_BT_ORBIT_LEFT,
    CAMERA_BT_ORBIT_RIGHT,
    CAMERA_BT_ZOOM_IN,
    CAMERA_BT_ZOOM_OUT,
    CAMERA_BT_RESET,

    CAMERA_BT_COUNT
};

enum IPlayerButtons
{
    PLAYER_BT_FORWARD,
    PLAYER_BT_BACKWARD,
    PLAYER_BT_LEFT,
    PLAYER_BT_RIGHT,
    PLAYER_BT_JUMP,
    PLAYER_BT_ATTACK,
    PLAYER_BT_RUN,
    PLAYER_BT_DUCK,

    PLAYER_BT_COUNT
};